apiVersion: v1
kind: PersistentVolume
metadata:
  name: vault-backups
spec:
  capacity:
    storage: 1Mi
  accessModes:
    - ReadWriteMany
  nfs:
    server: "<server-ip>"
    path: /<path>/kubernetes-persistent-volumes/vaultwarden-backups
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vault-backups
  namespace: vaultwarden
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 1Mi
  volumeName: vault-backups
